language: python
python:
    - "2.7"

branches:
    only:
        - develop

services:
    - docker

sudo:
    - required

before_install:
    - docker pull ubuntu:16.04
    - docker-compose up --build -d -f Dockerfile

    - sudo apt-get purge python-openssl
    - sudo apt-get install libffi-dev
    - sudo pip install pyopenssl

install:
    - echo '\n\n' | python ./install/install.py
    - rm -rf ./tests
    - git clone https://github.com/owtf/owtf_testing
    - source /usr/local/bin/virtualenvwrapper.sh
    - workon owtf
    - pip install --upgrade -r ./owtf_testing/owtf_testing.pip

before_script:
    - cp -f ./owtf_testing/profiles/plugin_web/groups.cfg ./profiles/plugin_web/groups.cfg
    - cp -f ./owtf_testing/profiles/plugin_net/groups.cfg ./profiles/plugin_net/groups.cfg
    - cp -f ./owtf_testing/profiles/plugin_aux/groups.cfg ./profiles/plugin_aux/groups.cfg
    - git config --global user.email "tasty@mac.test"
    - git config --global user.name "Tasty Test"
    - git am < ./owtf_testing/patch/0001-unittest-Patch-to-reuse-proxy-address.patch
    - ./owtf_testing/patch/skipfish.sh

script:
    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.cli.test_simulation.OWTFCliSimulationTest.test_cli_simulation
    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.cli.test_simulation.OWTFCliSimulationTest.test_cli_no_simulation

    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.cli.test_nowebui.OWTFCliNoWebUITest.test_cli_no_webui

    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.cli.test_empty_run.OWTFCliEmptyRunTest.test_cli_empty_run

    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.cli.test_list_plugins.OWTFCliListPluginsTest.test_cli_list_plugins_aux
    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.cli.test_list_plugins.OWTFCliListPluginsTest.test_cli_list_plugins_net
    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.cli.test_list_plugins.OWTFCliListPluginsTest.test_cli_list_plugins_web

    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.cli.test_only.OWTFCliOnlyPluginsTest.test_only_one_plugin
    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.cli.test_only.OWTFCliOnlyPluginsTest.test_only_one_plugin_one_type

    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.cli.test_except.OWTFCliExceptTest.test_except

    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.cli.test_scope.OWTFCliScopeTest.test_cli_target_is_valid_ip
    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.cli.test_scope.OWTFCliScopeTest.test_cli_target_is_invalid
    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.cli.test_scope.OWTFCliScopeTest.test_cli_target_is_valid_http
    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.cli.test_scope.OWTFCliScopeTest.test_cli_target_are_mixed
    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.cli.test_scope.OWTFCliScopeTest.test_cli_target_are_mixed_but_web_specified
    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.cli.test_scope.OWTFCliScopeTest.test_cli_target_are_mixed_but_net_specified

    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.cli.test_type.OWTFCliTypeTest.test_cli_type_no_group_and_type_when_http_host
    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.cli.test_type.OWTFCliTypeTest.test_cli_type_no_group_and_type_when_host
    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.cli.test_type.OWTFCliTypeTest.test_cli_type_no_group_and_type_when_http_ip
    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.cli.test_type.OWTFCliTypeTest.test_cli_type_no_group_and_type_when_ip

    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.plugins.web.test_web.OWTFCliWebPluginTest.test_web_active
    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.plugins.web.test_web.OWTFCliWebPluginTest.test_web_passive
    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.plugins.web.test_web.OWTFCliWebPluginTest.test_web_semi_passive
    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.plugins.web.test_web.OWTFCliWebPluginTest.test_web_external
    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.plugins.web.test_web.OWTFCliWebPluginTest.test_web_grep

    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.plugins.web.active.test_web_active.OWTFCliWebActivePluginTest.test_web_active_wvs_001
    - sudo $WORKON_HOME/owtf/bin/python -m unittest owtf_testing.tests_functional.plugins.web.active.test_web_active.OWTFCliWebActivePluginTest.test_web_active_wvs_006

notifications:
    email: false
    irc:
        channels:
            - "irc.freenode.net#owtf"
        on_success: change
        on_failure: always
        use_notice: true
