version: "3.3"
services:
  db:
    container_name: owtf_db
    image: postgres:alpine
    ports:
      - 5342:5432
    environment:
      - POSTGRES_USER=owtf_db_user
      - POSTGRES_PASSWORD=jgZKW33Q+HZk8rqylZxaPg1lbuNGHJhgzsq3gBKV32g=
      - POSTGRES_DB=owtf_db
